# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rmultinomRcpp <- function(probs) {
    .Call('_zinLDA_rmultinomRcpp', PACKAGE = 'zinLDA', probs)
}

findStringLoc <- function(inputVector, id) {
    .Call('_zinLDA_findStringLoc', PACKAGE = 'zinLDA', inputVector, id)
}

bSumRcpp <- function(b_, nw_, w_, V_, k_) {
    .Call('_zinLDA_bSumRcpp', PACKAGE = 'zinLDA', b_, nw_, w_, V_, k_)
}

sampleZProbRcpp <- function(d, w, kVect, delta, nw, nd, ndsum, K, a, b, alpha, V) {
    .Call('_zinLDA_sampleZProbRcpp', PACKAGE = 'zinLDA', d, w, kVect, delta, nw, nd, ndsum, K, a, b, alpha, V)
}

gibbSampleZRcpp <- function(D, z, nw, nd, ndsum, kVect, delta, K, a, b, alpha, V) {
    .Call('_zinLDA_gibbSampleZRcpp', PACKAGE = 'zinLDA', D, z, nw, nd, ndsum, kVect, delta, K, a, b, alpha, V)
}

